// <auto-generated />
namespace courseProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addCarLevelOnTrips : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCarLevelOnTrips));
        
        string IMigrationMetadata.Id
        {
            get { return "201905132340543_addCarLevelOnTrips"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
